
;--- Play CD Audio with Cxh/Bxh commands on SoundBlaster 16/16ASP.
;--- Public Domain, written by Andreas Grech.

	.286
	.MODEL small
	.dosseg
	.stack 2048
	option casemap:none
	option proc:private
	.386

;--- defaults ( overwritten by BLASTER environment variable )
BASEADDR	EQU 220h	; base address
SBIRQ		EQU 5		; IRQ
DMALOW		EQU 1		; DMA channel
DMAHIGH 	EQU 5		; HDMA channel

;--- CD-ROM access

IOCREAD  equ 03h     ;ioctl read cmd
READLONG equ 80h     ;real long cmd

IO_VOLSIZE   equ 8   ;ioctl get volume size
IO_DISKINFO  equ 10  ;ioctl get disk info
IO_TRKINFO   equ 11  ;ioctl get track info

HSG_MODE equ 00h
RB_MODE  equ 01h

COOKED   equ 00h
RAW      equ 01h

reqhdr  struct
len     db ?
subunit db ?
cmd     db ?
status  dw ?
res1    dd ?
res2    dd ?
reqhdr  ends

cmd03   struct      ;read ioctl
        reqhdr <>
mdesc   DB   ?      ; block devices: Media descriptor byte from BPB
taddr   DD   ?      ; Transfer address
numbyt  DW   ?      ; call: # bytes to transfer; return: # bytes transfered
cmd03   ends

cmd80   struct
        reqhdr <>
mode    db ?         ;addressing mode (0=HSG,1=red book)
address dd ?         ;transfer address
numsecs dw ?         ;number of sectors to read
stasecs dd ?         ;start of sectors to read
readmod db ?         ;00=cooked (2048),01=raw (2356)
intsize db ?         ;interleave
intskip db ?         ;interleave
cmd80   ends

;----------------------

PGMNAME textequ <"SB16CDr">

BIOSTIMER equ 46Ch	; BIOS data address of current PIT value

lf equ 10

	include dma.inc
	include sbequ.inc

; DMA WRITE MODE
WANTEDMODE  EQU DMA_MODE_SINGLE + DMA_MODE_AUTOINIT + DMA_MODE_READ

CStr macro text:vararg
local sym
	.const
sym db text,0
	.code
	exitm <offset sym>
endm

WaitRead macro
LOCAL loopWait
	push cx
	xor cx, cx
loopWait:
	in al, dx
	test al,80h
	loopzw loopWait		; Jump if bit7=0 - no data available
	pop cx
endm

WaitWrite macro
LOCAL loopWait
	push cx
	xor cx,cx
loopWait:
	in al, dx
	test al, 80h
	loopnzw loopWait	; Jump if bit7=1 - writing not allowed
	pop cx
endm

WriteDSP macro Base, cmd
	mov dx, Base
	add dx, SB_DSPWRITE
	WaitWrite
	mov al, cmd
	out dx, al
endm

?SECSIZE equ 2352

SAMPLEBUFFERLENGTH equ ?SECSIZE*4

	.data

OldIntSB    dd 0
dwSampleBuffer dd 0   ; linear address sample buffer
dwChunks	dd 0
pSampleBuffer dw offset samplebuffer ; near ptr sample buffer
wBase		dw BASEADDR
wIrq		dw SBIRQ
wDmaL		dw DMALOW
wDmaH		dw DMAHIGH
wType		dw 0
wOldMask	dw 0

bInit		db 0
bVerbose	db 1
bHelp		db 0
bReady		db 0

	align word

wDmaBaseChn dw 0
wDmaCntChn  dw 0
wDmaPageChn dw 0
wDmaWriteMask dw 0
wDmaWriteMode dw 0
wDmaClearFlipFlop dw 0
wDrive dw 0
wBitsPerSample dw 16
nSamplesPerSec dd 44100

req03   cmd03  <>	;ioctl
req80   cmd80  <>	;read long

	.data?

samplebuffer db SAMPLEBUFFERLENGTH * 2 dup (?)

	.const

pgtab db 87h, 83h, 81h, 82h, -1, 8bh, 89h, 8ah

szHelp label byte
	db PGMNAME," - read Audio CD data and send it to the SB16.",lf
	db "Usage: ",PGMNAME," [options] [track#]",lf
	db " options:",lf
	db " -? : this help",lf
	db " -q : be quiet",lf
	db "If track# is omitted, all tracks are rendered.",lf
	db "Stop playing with <ESC>.",lf
	db 0

	.code

dsseg dw 0

	include printf.inc

;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; Our IRQ handler for detecting end of playing
; It's generated by the SoundBlaster hardware
;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
sbirqproc proc
	push ax
	push dx
	push ds
	mov ds, cs:[dsseg]
	mov [bReady], 1
if 0	; debugging
	push bx
	mov bh,0
	mov ax,0E00h or '.'
	int 10h
	pop bx
endif
	mov dx, [wBase]
if 1
	mov ax, SB_DSPINTACK	; VSB is happy with 22Eh or 22Fh, but real SB needs 22Eh for 8 bit!
	cmp wDmaBaseChn, 10h
	jb @F
endif
	mov ax, SB16_DSPINTACK
@@:
	add dx, ax
	in al, dx
	mov al, 020h
	cmp [wIrq], 8
	jb @F
	out 0A0h, al
@@:
	out 020h, al
	pop ds
	pop dx
	pop ax
	sti
	IRET
sbirqproc endp

GetEnvironmentVariable proc stdcall uses es si di pVar:ptr, pOut:ptr, wSize:word

	mov ah, 51h
	int 21h
	mov es, bx
	mov es, es:[2Ch]
	xor di, di
	mov si, pVar
	mov bx, si
	.while byte ptr [bx]
		inc bx
	.endw
	sub bx, si
nextvar:
	mov cx, bx
	push si
	push di
	repz cmpsb
	jz found
skipvar:
	pop di
	pop si
	mov al, 0
	or cx,-1
	repnz scasb
	cmp byte ptr es:[di],0
	jnz nextvar
	xor ax, ax
	ret
found:
	cmp byte ptr es:[di],'='
	jnz skipvar
	add sp, 2*2
	inc di
	mov si, di
	mov di, pOut
	mov cx, wSize
	mov bx, ds
	push es
	pop ds
	mov es, bx
@@:
	lodsb
	stosb
	cmp al,0
	loopnz @B
	mov ds, bx
	mov ax, di
	sub ax, pOut
	ret
GetEnvironmentVariable endp

;--- convert string to number
;--- si:src text
;--- cl:base (10/16)
;--- out:number in EAX
;---     si -> behind number
;--- Z if no valid digit found

getnum proc uses bx
	mov bx, si
	xor edx, edx
	movzx ecx, cl
nextdigit:
	lodsb
	sub al, '0'
	jb exit
	cmp al, 9
	jbe ok
	cmp cl, 16
	jnz exit
	sub al, 7
	cmp al, 15
	ja exit
ok:
	imul edx, ecx
	movzx eax, al
	add edx, eax
	jmp nextdigit
exit:
	dec si
	mov eax, edx
	cmp si, bx
	ret
getnum endp

;--- scan BLASTER variable, overwrite
;--- default values in wBase, wIrq, wDmaL, wDmaH, wType

ScanBlasterVar proc stdcall uses si pVar:ptr
	mov si, pVar
	or bx, -1
	.while (byte ptr [si])
		lodsb
		.if (al == ' ')
			or bx,-1
			.continue
		.endif
		.if ((al >= 'a') && (al <= 'z'))
			sub al,20h
		.endif
		.if (bx == -1)
			mov cl,16
			.if (al == 'A')
				mov bx, offset wBase
			.elseif (al == 'I')
				mov bx, offset wIrq
				mov cl,10
			.elseif (al == 'D')
				mov bx, offset wDmaL
			.elseif (al == 'H')
				mov bx, offset wDmaH
			.elseif (al == 'T')
				mov bx, offset wType
			.endif
			.continue
		.endif
		dec si
		call getnum
		jz numdone
		.if (bx != -1)
			mov [bx], ax
		.endif
numdone:
	.endw
	ret
ScanBlasterVar endp

;--- send device driver request

SendReq proc stdcall req:ptr BYTE

	mov bx,req
	push ds
	pop es
	mov cx,wDrive
	clc 			;XP needs this
	mov ax,1510h	;send dev. req.
	int 2Fh
	ret

SendReq endp

;--- check CD.
;--- returns: NC: ok
;---           C: no audio CD

ioctl08 struct	;get volume size
cmd     db ?
sectors dd ?	;size in sectors
ioctl08 ends

getvolsize proc

local ctl08:ioctl08

;--- get volume size
	mov req03.len, sizeof cmd03
	mov req03.cmd, IOCREAD
	lea ax, ctl08
	mov word ptr req03.taddr+0, ax
	mov word ptr req03.taddr+2, ss
	mov req03.numbyt, sizeof ioctl08
	mov ctl08.cmd, IO_VOLSIZE	;get volume size
	mov ctl08.sectors, 0
	invoke SendReq, addr req03
	jc error
	test req03.status, 8000h
	jnz error
	.if bVerbose
		invoke printf, CStr("IOCTL volume size: [%X] sectors=%lu",lf), req03.status, ctl08.sectors
	.endif
	mov eax, ctl08.sectors
	clc
	ret
error:
	invoke printf, CStr("IOCTL volume size: failed [%X]",lf), req03.status
	mov eax, -1
	clc
	ret

getvolsize endp

ioctl10 struct	;audio disk info
cmd     db ?
first   db ?
last    db ?
union
leadout dd ?
struct
leadout_f db ?
leadout_s db ?
leadout_m db ?
ends
ends
ioctl10 ends

getdiskinfo proc

local ctl10:ioctl10

	mov req03.len, sizeof cmd03
	mov req03.cmd, IOCREAD
	lea ax, ctl10
	mov word ptr req03.taddr+0, ax
	mov word ptr req03.taddr+2, ss
	mov req03.numbyt, sizeof ioctl10
	mov ctl10.cmd, IO_DISKINFO
	invoke SendReq, addr req03
	jc error
	test req03.status, 8000h
	jnz error
	.if bVerbose
		invoke printf, CStr("IOCTL disk info: [%X] tracks=%u-%u, leadout=%02u:%02u:%02u",lf),
			req03.status, ctl10.first, ctl10.last, ctl10.leadout_m, ctl10.leadout_s, ctl10.leadout_f
	.endif
	mov al, ctl10.first
	mov ah, ctl10.last
	clc
	ret
error:
	invoke printf, CStr("IOCTL disk info: failed [%X]",lf), req03.status
	stc
	ret

getdiskinfo endp

ioctl11 struct	;audio track info
cmd     db ?
track   db ?
union
start   dd ?
struct
start_f db ?
start_s db ?
start_m db ?
ends
ends
ctlinfo db ?    ; bit 6=1 -> data track
ioctl11 ends

gettrackinfo proc stdcall track:word

local ctl11:ioctl11

	mov req03.len, sizeof cmd03
	mov req03.cmd, IOCREAD
	lea ax, ctl11
	mov word ptr req03.taddr+0, ax
	mov word ptr req03.taddr+2, ss
	mov req03.numbyt, sizeof ioctl11
	mov ctl11.cmd, IO_TRKINFO
	mov ax, track
	mov ctl11.track, al
	invoke SendReq, addr req03
	jc error
	test req03.status, 8000h
	jnz error
	test ctl11.ctlinfo, 40h
	jnz error2
	mov eax, ctl11.start
	call CvtLBA   ; convert RedBook in EAX to LBA
	.if bVerbose
		push eax
		mov ecx, eax
		invoke printf, CStr("IOCTL track info(%u): [%X] start=%lu (RedBook=%02u:%02u:%02u)",lf),
        	track, req03.status, ecx, ctl11.start_m, ctl11.start_s, ctl11.start_f
		pop eax
	.endif
	ret
error:
	invoke printf, CStr("IOCTL track info(%u): failed [%X]",lf), track, req03.status
	stc
	ret
error2:
	invoke printf, CStr("IOCTL track info(%u): [%X] data track",lf), track, req03.status
	stc
	ret
gettrackinfo endp

;--- read CD
;--- out: NC: read ok, eax=bytes read

cdread proc stdcall pBuffer:ptr

	mov dx, pBuffer
	test dwChunks, 1
	jz @F
	add dx, SAMPLEBUFFERLENGTH shr 1
@@:
	mov req80.len,sizeof cmd80
	mov req80.subunit,00
	mov req80.cmd,READLONG
	mov req80.mode,HSG_MODE
	mov word ptr req80.address+0, dx
	mov word ptr req80.address+2, ds
	mov word ptr req80.numsecs+0, (SAMPLEBUFFERLENGTH shr 1) / ?SECSIZE
	mov word ptr req80.readmod, RAW

	invoke SendReq, addr req80
	jc error
	test req80.status, 8000h
	jnz error
	add req80.stasecs, (SAMPLEBUFFERLENGTH shr 1) / ?SECSIZE
	inc dwChunks
	movzx eax, ax
	ret
error:
	invoke printf, CStr("Read long(%lu): failed [%X]",lf), req80.stasecs, req80.status
	stc
	ret
cdread endp

;--- set DMA registers
;--- WRITEMASK      DMABase + 10 * DMAWidth
;--- WRITEMODE      DMABase + 11 * DMAWidth
;--- CLEARFLIPFLOP  DMABase + 12 * DMAWidth
;--- BASE_CHN       DMABase + DMAWidth * channel
;--- COUNT_CHN      DMABase + DMAWidth * channel + DMAWidth
;--- PAGE_CHN       channel PAGE

setdmaports proc uses ebx

	movzx ebx, wDmaH
	mov edx, 0	; edx=DMABase (0/C0)
	mov ecx, 1	; ecx=DMAWidth (1/2)
	cmp ebx, 4
	jb @F
	mov dx, 0C0h
	inc ecx
@@:
	mov eax, 10			; single mask register
	imul eax, ecx
	add eax, edx
	mov wDmaWriteMask, ax ; bits 0-1 select channel, bit 2 sets status
	mov ax, 11			; mode register
	imul eax, ecx
	add eax, edx
	mov wDmaWriteMode, ax
	mov ax, 12			; flip flop
	imul eax, ecx
	add eax, edx
	mov wDmaClearFlipFlop, ax
	mov al, [ebx+pgtab]	; al=page register
	mov ah, 0
	mov wDmaPageChn, ax
	mov eax, ebx
	and al, 3
	shl eax, 1
	imul eax, ecx
	add eax, edx
	mov wDmaBaseChn, ax	; address register
	add eax, ecx
	mov wDmaCntChn, ax	; cnt register
	ret
setdmaports endp

GetDmaChannel proc
	mov al, byte ptr wDmaH
	sub al, 4
	ret
GetDmaChannel endp

;--- get linear address and offset of sample buffer.
;--- (must not cross a 64-kB boundary)
;--- linear address (=dwSampleBuffer) is used for DMAcontroller page & offset
;--- offset address (=pSampleBuffer) is used for file reads

getsamplebufferaddr proc uses esi

	mov ax, ds
	movzx eax,ax
	shl eax, 4
	add eax, offset samplebuffer

	mov esi, eax
	mov ecx, SAMPLEBUFFERLENGTH
	lea eax, [esi+ecx-1]
	mov edx, esi
	shr eax, 16
	shr edx, 16
	cmp ax, dx				;does a 64kb segment overrun occur?
	jz @F

	shl eax, 16
	mov edx, eax			;eax & edx = linear address of 64kb segment to use
	sub edx, esi			;edx = difference to linear address of original sample buffer
	add [pSampleBuffer], dx	;adjust offset

	mov esi, eax
@@:
	mov eax, esi

	mov [dwSampleBuffer], eax
	clc
	ret

getsamplebufferaddr endp

;--- return #samples in one half of sample buffer (ecx).
;--- this will be the value for the DSP play cmd.
;--- stereo are 2 samples, so just the bits/sample are relevant.
;--- edx must be preserved.

getsamplebufferlength proc

	mov ecx, SAMPLEBUFFERLENGTH shr 1
	shr ecx, 1
	ret
getsamplebufferlength endp

if 0
dispdmastatus proc
	xor ecx, ecx
	mov dx, [wDmaCntChn]
	in al, dx
	mov cl, al
	in al, dx
	mov ch, al
	xor eax, eax
	mov dx, [wDmaPageChn]
	in al, dx
	shl eax, 16
	mov dx, [wDmaBaseChn]
	in al, dx
	mov ah, al
	in al, dx
	xchg al, ah
	cmp dx, 10h
	mov dx, 8
	jb @F
;	shl eax, 1
	shl ax, 1		; don't modify the page register value in bits 16-23
	shl ecx, 1
	mov dx, 0D0h
@@:
	push ax
	in al, dx
	movzx dx, al
	pop ax
	invoke printf, CStr("DMA ofs=%lX cnt=%lX stat=%X   ",13), eax, ecx, dx
	ret
dispdmastatus endp
endif

ResetDSP proc
	mov dx, [wBase]
	add dx, SB_DSPRESET
	mov al, 1
	out dx, al			; start DSP reset

	in al, dx
	in al, dx
	in al, dx
	in al, dx			; wait 3 æsec

	xor al, al
	out dx, al			; end DSP Reset

	mov dx, [wBase]
	add dx, SB_DSPSTATUS
	WaitRead
	mov dx, [wBase]
	add dx, SB_DSPREAD
	in al, dx
	cmp al, 0aah		; if there is a SB then it returns 0AAh
	je @F
	stc
	ret
@@:
	clc
	ret
ResetDSP endp

ReadDSPWord proc stdcall bCmd:byte

	WriteDSP [wBase], bCmd
	mov dx, [wBase]
	add dx, SB_DSPSTATUS
	WaitRead
	mov dx, [wBase]
	add dx, SB_DSPREAD
	in al, dx
	mov ah, al
	mov dx, [wBase]
	add dx, SB_DSPSTATUS
	WaitRead
	mov dx, [wBase]
	add dx, SB_DSPREAD
	in al, dx
	ret

ReadDSPWord endp

;--- convert redbook address in EAX to LBA

CvtLBA proc
	mov cx,ax		;Save "seconds" & "frames" in CX-reg.
	shr eax,16		;"minute" value to AX
	cmp ax,99		;Is "minute" value too large?
	ja error
	cmp ch,60		;Is "second" value too large?
	ja error
	cmp cl,75		;Is "frame" value too large?
	ja error

;--- convert minute value to seconds
	mov edx,60
	mul dl
	mov dl,ch		;add "second" value.
	add ax,dx		;now ax contains seconds

;--- convert seconds to frames
	mov dl,75
	mul edx
	mov dl,150		;add "frame" value by subtracting it from "2 sec" offset
	sub dl,cl
	sub eax,edx
	ret
error:
	mov eax,100*60*75	;error, set value to max (450.000)
	ret
CvtLBA endp

;--- get current PIT timer 0 value

gettimer proc uses ds
	mov ax, 0
	mov ds, ax
	mov eax, ds:[BIOSTIMER]
	ret
gettimer endp

;--- init SB hardware, including ISA DMA

InitSB proc

	cmp bInit, 1
	jz exit    

;--- init SB and DMA hardware

	call ResetDSP
	.if CARRY?
		invoke printf, CStr('No SoundBlaster found at 0x%x',lf), [wBase]
		stc
		ret
	.endif

;--- check if it's a SB16
	invoke ReadDSPWord, DSP_VERSION
	.if ax < 400h
		invoke printf, CStr('No SB16 found, DSP version=%X',lf), ax
		stc
		ret
	.endif

	mov bInit, 1

;--- setup isr

	WriteDSP [wBase], DSP_ENABLESPEAKER

	mov al, byte ptr [wIrq]
	.if ( al < 8 )
		add al, 8
	.else
		add al, 68h
	.endif
	push es
	mov ah, 35h
	int 21h
	mov word ptr [OldIntSB+0], bx
	mov word ptr [OldIntSB+2], es
	pop es
	push ds
	push cs
	pop ds
	mov dx, offset sbirqproc
	mov ah, 25h
	int 21h
	pop ds

;--- enable sound IRQ

	in al, 021h
	mov ah, al
	in al, 0A1h
	xchg al,ah
	mov wOldMask, ax

	mov dx, 21h
	mov bx, [wIrq]
	cmp bx, 8
	jb @F
	mov dx, 0A1h
	sub bx, 8
@@:
	in al, dx
	btr ax, bx
	out dx, al

;--- Setup DMA-controller
	call setdmaports
	.if bVerbose
		invoke printf, CStr("DMA ports addr/cnt/page=%X/%X/%X",lf), wDmaBaseChn, wDmaCntChn, wDmaPageChn
	.endif

;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; 1st  MASK DMA CHANNEL
;
	call GetDmaChannel
	or al, DMA_MASK_DISABLE_CHN	; bit 2 sets mask, bits 0-1 select channel
	mov dx, wDmaWriteMask
	out dx, al
;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; 2nd  CLEAR FLIPFLOP
;
	mov dx, wDmaClearFlipFlop
	out dx, al
;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; 3rd  WRITE TRANSFER MODE
;
	call GetDmaChannel
	or al, WANTEDMODE
	mov dx, wDmaWriteMode
	out dx, al
;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; 4th  WRITE PAGE NUMBER
;
	mov esi, [dwSampleBuffer]

	mov eax, esi
	shr eax, 16
;	cmp wDmaBaseChn, 10h
;	jb @F
;	shr eax, 1	; for 16-bit DMA, skip lowest bit
;@@:
	mov dx, wDmaPageChn
	out dx, al
;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; 5th  WRITE BASEADDRESS
;
	mov eax, esi
	mov dx, wDmaBaseChn
	cmp dx, 10h
	jb @F
	shr eax, 1	; for 16-bit DMA, skip lowest bit
@@:
	out dx, al
	mov al, ah
	out dx, al
;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; 6th  WRITE SAMPLELENGTH-1
;
	mov dx, wDmaCntChn
	mov ecx, SAMPLEBUFFERLENGTH
	cmp dx, 10h
	jb @F
	shr ecx, 1	; for 16-bit DMA, skip lowest bit
@@:
	dec ecx
	mov al, cl
	out dx, al
	mov al, ch
	out dx, al
;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; 7th  DEMASK CHANNEL
;
	call GetDmaChannel
	or al, DMA_MASK_ENABLE_CHN	; this is actually zero
	mov dx, wDmaWriteMask
	out dx, al

;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; Setup SoundBlaster :
;
; 1st  SET SAMPLERATE
;
	WriteDSP [wBase], DSP_SETOUTSAMPLERATE
	mov ecx, nSamplesPerSec
	WaitWrite
	mov al,ch
	out dx,al
	WaitWrite
	mov al,cl
	out dx,al
;ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
; 2nd  play 8/16bit stereo (B6 30)/mono (C6 00) XX XX
;
	WaitWrite
	mov ax, 030B6h				;B6,30 = DMA DAC 16bit autoinit, stereo, signed
	cmp wBitsPerSample, 16
	jz @F
	mov ax, 000C6h				;C6,00 = DMA DAC 8bit autoinit, mono, unsigned
@@:
	out dx, al
	WaitWrite
	mov al, ah					;AL = stereo signed / mono unsigned
	out dx, al
	call getsamplebufferlength
	dec ecx
	WaitWrite
	mov al, cl					; LOWER PART SAMPLELENGTH
	out dx, al
	WaitWrite
	mov al, ch					; HIGHER PART SAMPLELENGTH
	out dx, al
	clc
exit:
	ret

InitSB endp

;--- deinit SB hardware

ExitSB proc

	cmp bInit, 0
	jz exit    
	call ResetDSP
;--- restore PIC masks
	mov ax, wOldMask
	out 21h, al
	mov al, ah
	out 0A1h, al

;--- RESTORE IRQ
	mov al, byte ptr [wIrq]
	.if ( al < 8 )
		add al, 8
	.else
		add al, 68h
	.endif
	push ds
	lds dx, [OldIntSB]
	mov ah, 25h
	int 21h
	pop ds
exit:
	ret
ExitSB endp

main proc c argc:word, argv:ptr

local dwTimer:dword
local dwSectors:dword
local track:byte
local lasttrack:byte
local szVar[64]:byte

	mov cs:[dsseg], ds
	push ds
	pop es
	mov track,0

;--- get BLASTER settings

	invoke GetEnvironmentVariable, CStr("BLASTER"), addr szVar, sizeof szVar
	.if ax
		invoke ScanBlasterVar, addr szVar
	.endif

;--- CD-ROM installed?

	mov ax,1500h
	mov bx,0000
	int 2Fh
	cmp bx,0000
	jnz cd_found
	invoke printf, CStr("no CD-ROM drive found",lf)
	jmp exit
cd_found:
	mov wDrive, cx

	mov req80.stasecs,0

	add argv, 2
	mov bx, argv
nexttrack:
	.while word ptr [bx]
		mov si, [bx]
		add bx, 2
		lodsw
		.if al >= '0' && al <= '9'
			sub si,2
			mov cl,10
			call getnum
			.if byte ptr [si]
				invoke printf, CStr("invalid digit: %s",lf), si
				jmp exit
			.endif
			mov track, al
			.break
		.elseif al == '/' || al == '-'
			or ah,20h
			.if ah == "q"
				mov bVerbose, 0
			.else
				mov bHelp, 1
			.endif
		.else
			mov bHelp, 1
		.endif
	.endw
	mov argv, bx

	cmp bHelp, 0
	jz @F
	invoke printf, CStr("%s"), offset szHelp
	jmp exit
@@:

;--- get volume size info (# of sectors)

	invoke getvolsize
	jc exit
	mov dwSectors, eax

;--- get TOC info ( first track, last track) in AL/AH
	invoke getdiskinfo
	mov lasttrack, ah

	.if track
		invoke gettrackinfo, track
		jc exit
		mov req80.stasecs, eax
		movzx ax, track
		.if al < lasttrack
			inc al
			invoke gettrackinfo, ax
			mov dwSectors, eax
		.endif
	.endif

	.if bVerbose
		invoke printf, CStr("SB base=%X, irq=%u, dma=%u, hdma=%u",lf), wBase, wIrq, wDmaL, wDmaH
	.endif

;--- set linear address (dwSampleBuffer) and offset (pSampleBuffer) of sample buffer

	call getsamplebufferaddr
	jc exit
	.if bVerbose
		invoke printf, CStr("sample buffer linear address=%lX",lf), [dwSampleBuffer]
	.endif

;--- fill sample buffer

	mov si, [pSampleBuffer]
	invoke cdread, si
	jc exit
	invoke cdread, si
	jc exit

;--- init SB hardware

	call InitSB
	jc exit

	call gettimer
	mov dwTimer, eax
waitloop:
	.if bVerbose
		call gettimer
		sub eax, dwTimer
		cmp eax, 5
		jb @F
		add dwTimer, eax
		invoke printf, CStr("curr sector: %lu",13), req80.stasecs
@@:
	.endif
	mov ah,01			; key pressed?
	int 16h
	jz @F
	mov ah,0
	int 16h
	cmp ah,1
	jz exit
@@:
	cmp [bReady],0		; SB interrupt occured?
	jz waitloop
	mov [bReady],0
	mov eax, dwSectors
	cmp eax, req80.stasecs
	jbe done
	invoke cdread, pSampleBuffer
	jc exit
	jmp waitloop
done:
;--- wait till the last half has been played
@@:
	cmp [bReady],0
	jz @B
	.if bVerbose
		invoke printf, CStr(10)
	.endif
	mov bx, argv
	cmp word ptr [bx],0
	jnz nexttrack
exit:
	call ExitSB
	ret

main endp

	include setargv.inc

start:
	mov ax,@data
	mov ds,ax
	mov cx,ss
	sub cx,ax
	shl cx,4
	mov ss,ax
	add sp,cx
	call _setargv
	invoke main, [_argc], [_argv]
	mov ax,04c00h
	int 21h

	END start
